spring:

  servlet:
    session:
      tracking-modes : cookie
      timeout : 3600

    multipart:
      max-file-size: 15MB
      max-request-size: 100MB



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aws-rds.cyeqzizjffgt.ap-northeast-2.rds.amazonaws.com/hair_review
    username: admin
    password: kkt1326!

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

cloud:
  aws:
    # IAM 사용자 액세스, 비밀 키
    credentials:
      accessKey: AKIAWFB2UL6ZRAXEPR5J
      secretKey: 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
    s3:
      # s3 버킷 이름
      bucket: howhair
    region:
      # 지역
      static: ap-northeast-2
    stack:
      auto: false
    url : https://howhair.s3.ap-northeast-2.amazonaws.com

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  port: 3000

kakao:
  url: https://kapi.kakao.com/v2/user/me

aes:
  key: 12345678910111213
  alg: AES/CBC/PKCS5Padding